---
#Two Plays in Playbook

#Play 1 Get Variables - Create Backup - Deploy Configuration to ACI - Validate Configuration is present

- name: ACI BUILD JOB
  hosts: apic_group
  connection: local
  gather_facts: no

# prompting for username password for this Play
  vars_prompt:
    - name: "aci_user_id"
      prompt: "UserID"
      private: no


# PULLING IN VARIABLES FOR CONFIGURATION
# Can change the directory as needed 
  tasks:
    - name: OBTAIN CONFIG VARIABLES
      include_vars: 
        file: ./tenant_vars/vmm_clean.yml


# this task removes the tenants to reset the test
    - name: TASK 1 - Cleanup Tenant
      aci_tenant:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_user_id }}"
        private_key: "~/{{ aci_user_id }}.key"
        tenant: "{{ item.tenant_var }}"
        validate_certs: no
        use_ssl: yes
        state: absent
      with_items: "{{ tenants }}"         
